[package]
name = "rhack"
version = "0.1.0"
authors = ["nakabonne <ryo@nakao.dev>"]
edition = "2018"
license-file = "LICENSE"
description = "Temporary edits to your Rust dependencies"
readme = "README.md"
homepage = "https://github.com/nakabonne/rhack"
repository = "https://github.com/nakabonne/rhack"
keywords = ["cli", "cargo", "dependency", "crate"]
categories = ["command-line-utilities"]

[dependencies]
anyhow = "1.0.52"
clap = { version = "3.0.5", features = ["derive", "color"] }
home = "0.5.3"
serde_json = "1.0.74"
serde = { version = "1.0.133", features = ["derive"] }
toml_edit = "0.12.3"
